from __future__ import annotations

CATEGORY_PROFILES = {
    "Fashion": {
        "elasticity_default": -1.45,
        "return_rate_default": 0.10,
        "competitor_sensitivity": 0.30,
        "target_margin_default": 0.32,
        "marketing_factor_default": 1.12,
        "monthly_bias": {
            1: 0.86,
            2: 0.92,
            3: 1.02,
            4: 1.14,
            5: 1.08,
            6: 0.98,
            7: 0.93,
            8: 0.97,
            9: 1.04,
            10: 1.08,
            11: 1.18,
            12: 1.22,
        },
    },
    "Jewelry": {
        "elasticity_default": -0.95,
        "return_rate_default": 0.04,
        "competitor_sensitivity": 0.17,
        "target_margin_default": 0.36,
        "marketing_factor_default": 1.08,
        "monthly_bias": {
            1: 0.90,
            2: 1.12,
            3: 0.96,
            4: 0.98,
            5: 1.02,
            6: 0.94,
            7: 0.91,
            8: 0.95,
            9: 1.0,
            10: 1.05,
            11: 1.16,
            12: 1.28,
        },
    },
    "Accessories": {
        "elasticity_default": -1.22,
        "return_rate_default": 0.06,
        "competitor_sensitivity": 0.26,
        "target_margin_default": 0.30,
        "marketing_factor_default": 1.10,
        "monthly_bias": {
            1: 0.88,
            2: 0.93,
            3: 0.99,
            4: 1.05,
            5: 1.03,
            6: 1.08,
            7: 1.14,
            8: 1.07,
            9: 1.0,
            10: 1.04,
            11: 1.11,
            12: 1.17,
        },
    },
    "Beauty": {
        "elasticity_default": -1.03,
        "return_rate_default": 0.055,
        "competitor_sensitivity": 0.21,
        "target_margin_default": 0.34,
        "marketing_factor_default": 1.09,
        "monthly_bias": {
            1: 0.94,
            2: 0.98,
            3: 1.08,
            4: 1.12,
            5: 1.04,
            6: 0.98,
            7: 0.95,
            8: 0.97,
            9: 1.01,
            10: 1.05,
            11: 1.09,
            12: 1.13,
        },
    },
}

COMPETITOR_NAMES = {
    "Fashion": ["Velora", "Northline", "Mira & Co"],
    "Jewelry": ["Gleam House", "Aurelia", "Nova Fine"],
    "Accessories": ["Carrywell", "Route Supply", "Tidal Goods"],
    "Beauty": ["DermaVale", "Glow Theory", "Fable Skin"],
}

PRODUCT_BLUEPRINTS = [
    {
        "product_id": "P1001",
        "name": "Aurora Satin Midi Dress",
        "category": "Fashion",
        "unit_cost": 34.0,
        "packaging_cost": 3.2,
        "base_price": 79.0,
        "base_monthly_demand": 240,
        "default_return_rate": 0.12,
        "elasticity": -1.62,
        "competitor_sensitivity": 0.32,
        "campaign_lift": 1.18,
    },
    {
        "product_id": "P1002",
        "name": "Harbor Linen Shirt",
        "category": "Fashion",
        "unit_cost": 22.0,
        "packaging_cost": 2.6,
        "base_price": 54.0,
        "base_monthly_demand": 320,
        "default_return_rate": 0.08,
        "elasticity": -1.35,
        "competitor_sensitivity": 0.28,
        "campaign_lift": 1.12,
    },
    {
        "product_id": "P1003",
        "name": "Contour Knit Set",
        "category": "Fashion",
        "unit_cost": 28.0,
        "packaging_cost": 3.0,
        "base_price": 68.0,
        "base_monthly_demand": 260,
        "default_return_rate": 0.10,
        "elasticity": -1.48,
        "competitor_sensitivity": 0.29,
        "campaign_lift": 1.14,
    },
    {
        "product_id": "P2001",
        "name": "Solstice Layered Necklace",
        "category": "Jewelry",
        "unit_cost": 14.0,
        "packaging_cost": 1.4,
        "base_price": 39.0,
        "base_monthly_demand": 360,
        "default_return_rate": 0.045,
        "elasticity": -1.02,
        "competitor_sensitivity": 0.18,
        "campaign_lift": 1.10,
    },
    {
        "product_id": "P2002",
        "name": "Pearl Drop Earrings",
        "category": "Jewelry",
        "unit_cost": 11.0,
        "packaging_cost": 1.2,
        "base_price": 34.0,
        "base_monthly_demand": 280,
        "default_return_rate": 0.038,
        "elasticity": -0.92,
        "competitor_sensitivity": 0.16,
        "campaign_lift": 1.09,
    },
    {
        "product_id": "P2003",
        "name": "Verve Signet Ring",
        "category": "Jewelry",
        "unit_cost": 17.0,
        "packaging_cost": 1.1,
        "base_price": 49.0,
        "base_monthly_demand": 220,
        "default_return_rate": 0.035,
        "elasticity": -0.88,
        "competitor_sensitivity": 0.14,
        "campaign_lift": 1.08,
    },
    {
        "product_id": "P3001",
        "name": "Luna Crossbody Bag",
        "category": "Accessories",
        "unit_cost": 26.0,
        "packaging_cost": 2.8,
        "base_price": 72.0,
        "base_monthly_demand": 250,
        "default_return_rate": 0.07,
        "elasticity": -1.24,
        "competitor_sensitivity": 0.27,
        "campaign_lift": 1.13,
    },
    {
        "product_id": "P3002",
        "name": "Atlas Travel Organizer",
        "category": "Accessories",
        "unit_cost": 12.0,
        "packaging_cost": 1.9,
        "base_price": 32.0,
        "base_monthly_demand": 340,
        "default_return_rate": 0.05,
        "elasticity": -1.18,
        "competitor_sensitivity": 0.24,
        "campaign_lift": 1.11,
    },
    {
        "product_id": "P3003",
        "name": "Nimbus Polarized Sunglasses",
        "category": "Accessories",
        "unit_cost": 18.0,
        "packaging_cost": 1.7,
        "base_price": 46.0,
        "base_monthly_demand": 380,
        "default_return_rate": 0.06,
        "elasticity": -1.29,
        "competitor_sensitivity": 0.30,
        "campaign_lift": 1.12,
    },
    {
        "product_id": "P4001",
        "name": "Radiant Vitamin C Serum",
        "category": "Beauty",
        "unit_cost": 9.0,
        "packaging_cost": 1.1,
        "base_price": 27.0,
        "base_monthly_demand": 480,
        "default_return_rate": 0.065,
        "elasticity": -1.09,
        "competitor_sensitivity": 0.22,
        "campaign_lift": 1.10,
    },
    {
        "product_id": "P4002",
        "name": "Restore Hair Mask",
        "category": "Beauty",
        "unit_cost": 8.5,
        "packaging_cost": 1.0,
        "base_price": 24.0,
        "base_monthly_demand": 420,
        "default_return_rate": 0.055,
        "elasticity": -1.01,
        "competitor_sensitivity": 0.20,
        "campaign_lift": 1.09,
    },
    {
        "product_id": "P4003",
        "name": "Daily Hydration Mist",
        "category": "Beauty",
        "unit_cost": 6.2,
        "packaging_cost": 0.9,
        "base_price": 19.0,
        "base_monthly_demand": 560,
        "default_return_rate": 0.048,
        "elasticity": -0.96,
        "competitor_sensitivity": 0.19,
        "campaign_lift": 1.08,
    },
]

DEFAULT_PRODUCT_ID = "P3001"
