DEFAULT_PRODUCT = {
    "name": "Smart Thermos Bottle",
    "category": "Home & Lifestyle",
    "unit_cost": 18.0,
    "fixed_cost": 3200.0,
    "base_price": 39.0,
    "competitor_price": 36.0,
    "base_demand": 420.0,
    "inventory": 500,
    "elasticity": -1.35,
    "marketing_budget": 1400.0,
    "return_rate": 0.06,
    "desired_margin": 28.0,
    "scenario": "NORMAL",
}

EMPTY_PRODUCT = {
    "name": "",
    "category": "",
    "unit_cost": "",
    "fixed_cost": "",
    "base_price": "",
    "competitor_price": "",
    "base_demand": "",
    "inventory": "",
    "elasticity": "",
    "marketing_budget": "",
    "return_rate": "",
    "desired_margin": "",
    "scenario": "NORMAL",
}

DEMO_PORTFOLIO_PRODUCTS = [
    DEFAULT_PRODUCT,
    {
        "name": "Wireless Ergonomic Mouse",
        "category": "Electronics",
        "unit_cost": 16.5,
        "fixed_cost": 2100.0,
        "base_price": 34.0,
        "competitor_price": 31.5,
        "base_demand": 560.0,
        "inventory": 650,
        "elasticity": -1.48,
        "marketing_budget": 900.0,
        "return_rate": 0.04,
        "desired_margin": 24.0,
        "scenario": "HIGH",
    },
    {
        "name": "Botanical Face Serum",
        "category": "Beauty",
        "unit_cost": 12.0,
        "fixed_cost": 1800.0,
        "base_price": 29.0,
        "competitor_price": 27.5,
        "base_demand": 390.0,
        "inventory": 420,
        "elasticity": -1.1,
        "marketing_budget": 1100.0,
        "return_rate": 0.07,
        "desired_margin": 31.0,
        "scenario": "PROMO",
    },
]
