DEFAULT_PRODUCT = {
    "name": "Luna Crossbody Bag",
    "category": "Accessories",
    "unit_cost": 26.0,
    "current_price": 72.0,
    "units_sold_30d": 250.0,
    "competitor_price": "",
    "scenario": "NORMAL",
    "elasticity_override": "",
    "return_rate_override": "",
    "fixed_cost_allocation_override": "",
    "target_margin_override": "",
    "marketing_factor_override": "",
    "inventory_constraint_override": "",
}

EMPTY_PRODUCT = {
    "name": "",
    "category": "",
    "unit_cost": "",
    "current_price": "",
    "units_sold_30d": "",
    "competitor_price": "",
    "scenario": "NORMAL",
    "elasticity_override": "",
    "return_rate_override": "",
    "fixed_cost_allocation_override": "",
    "target_margin_override": "",
    "marketing_factor_override": "",
    "inventory_constraint_override": "",
}

SEED_PORTFOLIO_PRODUCTS = [
    DEFAULT_PRODUCT,
    {
        "name": "Radiant Vitamin C Serum",
        "category": "Beauty",
        "unit_cost": 9.0,
        "current_price": 27.0,
        "units_sold_30d": 480.0,
        "competitor_price": "",
        "scenario": "HIGH",
        "elasticity_override": "",
        "return_rate_override": "",
        "fixed_cost_allocation_override": "",
        "target_margin_override": "",
        "marketing_factor_override": "",
        "inventory_constraint_override": "",
    },
    {
        "name": "Harbor Linen Shirt",
        "category": "Fashion",
        "unit_cost": 22.0,
        "current_price": 54.0,
        "units_sold_30d": 320.0,
        "competitor_price": "",
        "scenario": "PROMO",
        "elasticity_override": "",
        "return_rate_override": "",
        "fixed_cost_allocation_override": "",
        "target_margin_override": "",
        "marketing_factor_override": "",
        "inventory_constraint_override": "",
    },
]
